# DATABASE
spring:
   cloud:
      config:
         fail-fast: true
   datasource:
      url: jdbc:sqlserver://thanght.database.windows.net:1433;databaseName=FAS_DEV
      username: thanght
      password: "@Gcsvn123"
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
   jpa:
      show-sql: false
      generate-ddl: false
      hibernate:
         dialect: org.hibernate.dialect.SQLServer2017Dialect
         ddl-auto: none
# SERVICE REGISTRY
eureka:
   client:
      healthcheck:
          enabled: true
      registerWithEureka: true
      fetchRegistry: true
      registryFetchIntervalSeconds: 5
      #serviceUrl:
      #   defaultZone: https://fas-discovery-service.cfapps.io/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 30
      prefer-ip-address: false
      # https://cloud.spring.io/spring-cloud-netflix/multi/multi__service_discovery_eureka_clients.html
      # hostName: Fix error Zuul UnknownHostException(GUID)
      # nonSecurePort: Fix error Zuul not working due to Fowarding error
      hostName: ${vcap.application.uris[0]}
      nonSecurePort: 80
      securePortEnabled: true
      securePort: 443
      statusPageUrl: https://${eureka.hostname}/actuator/info
      healthCheckUrl: https://${eureka.hostname}/actuator/health
      homePageUrl: https://${eureka.hostname}
# FEIGN
feign:
   client:
      config:
         default:
            connectTimeout: 160000000
            readTimeout: 160000000
# UAA
ssoServiceUrl: https://fas-uaa.cfapps.io
security:
   basic:
      enabled: false
   oauth2:
      client:
         clientId: fasclient
         clientSecret: fasclientsecret
         accessTokenUri: ${ssoServiceUrl}/oauth/token
         userAuthorizationUri: ${ssoServiceUrl}/oauth/authorize
      resource:
         filter-order: 3
         userInfoUri: ${ssoServiceUrl}/userinfo
         preferTokenInfo: true
         tokenInfoUri: ${ssoServiceUrl}/oauth/check_token
         jwt:
            keyUri: ${ssoServiceUrl}/token_key
            keyValue: |
               -----BEGIN PUBLIC KEY-----
               MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnlYjPEoaAyj22XjyRflx
               Sgivn7tZC8258448ND0tvlRKvQ8mi//3wGfOEmd3X0wVhJXqv/5lzC8GYctVuolB
               DJ0ZBKDrE4/2Bira8RaLYEo+dpt/T9HNlcHgnFYF7f/4fYP0bHz7AUVDSje0ruQ4
               ZDsx5YoQ06dm/6OxPPXa3/maws6a9MWY7m86opzSKK3HnieHvjyxJylT0OM3lLkS
               rDaNh6NsJcCQQUOMjySHV0lR2fD5EgZ+/KoRVPz3V1n2b0m3xlKaFkAQL4OeH6Ri
               atNTfy9g3GaszvICrkrEnX6slC02wOHLkDzhwsfcgdVMv1tfoTFyP5jQnhiqkr4P
               OwIDAQAB
               -----END PUBLIC KEY-----
         id: fasclient
# LOGGING
logging:
   pattern:
      console: '%-5level %logger : %msg%n'
   level:
      org.springframework.web: ERROR
      org.hibernate: ERROR
      com.gcs.fas*: DEBUG
ribbon:
   ConnectTimeout: 600000
   ReadTimeout: 600000
zuul:
   ignored-services: '*'
   routes:
      data-transfer:
         path: /data-transfer/**
         service-id: fas-data-transfer-service
         strip-prefix: true
      management:
         path: /management/**
         service-id: fas-management-service
         strip-prefix: true
      device:
         path: /device/**
         service-id: fas-device-service
         strip-prefix: false
setting:
   useGateway: true
   logLevel: DEBUG